<script lang="ts">
    import { reportAppError } from './errorStore.svelte';
    import { initMarkdown, isHighlighterReady } from './markdown.svelte';
    import { streamingMarkdown } from './markdown-stream';

    let { content }: { content: string } = $props();

    // Triple-backtick is the only path that reaches Shiki; inline code and
    // 4-space indented blocks render through the plain <pre><code> fallback.
    let hasCodeBlock = $derived(content.includes('```'));

    $effect(() => {
        if (hasCodeBlock && !isHighlighterReady()) {
            initMarkdown().catch((err) => {
                reportAppError(
                    'syntax highlighter load failed',
                    "Couldn't load syntax highlighter",
                    err
                );
            });
        }
    });
</script>

<div
    class="prose prose-sm max-w-none"
    use:streamingMarkdown={{ content, highlighterReady: isHighlighterReady() }}
></div>

<style>
    /* Code block wrapper — holds the language label + Shiki <pre> */
    :global(.prose .code-block) {
        position: relative;
        margin-top: 0.5em;
        margin-bottom: 0.5em;
    }

    :global(.prose .code-header) {
        display: flex;
        align-items: center;
        justify-content: space-between;
        padding-bottom: 2px;
    }

    :global(.prose .code-lang) {
        display: inline-block;
        font-family: var(--font-mono);
        font-size: 0.7rem;
        font-style: normal;
        color: var(--color-fg-muted);
        padding: 0 2px;
    }

    :global(.prose .code-copy) {
        background: none;
        border: 1px solid var(--color-border);
        border-radius: 4px;
        color: var(--color-fg-muted);
        cursor: pointer;
        font-family: var(--font-mono);
        font-size: 0.7rem;
        line-height: 1;
        padding: 2px 7px;
        transition:
            color 0.1s,
            border-color 0.1s;
    }

    :global(.prose .code-copy:hover) {
        border-color: var(--color-fg-muted);
        color: var(--color-fg);
    }

    /* Shiki outputs <pre> with inline background — give it our surface token as fallback */
    :global(.prose pre) {
        background-color: var(--color-surface-sunken);
        border: 1px solid var(--color-border);
        margin-top: 0;
        margin-bottom: 0;
    }

    /* Inline code */
    :global(.prose code:not(pre code)) {
        background-color: var(--color-surface-sunken);
        border: 1px solid var(--color-border);
        border-radius: 4px;
        padding: 1px 5px;
        font-size: 0.8125em;
    }

    /* Remove the backtick pseudo-content typography adds */
    :global(.prose code:not(pre code))::before,
    :global(.prose code:not(pre code))::after {
        content: none;
    }

    :global(.prose blockquote) {
        border-left-color: var(--color-accent-fg);
        color: var(--color-fg-muted);
    }

    :global(.prose a) {
        color: var(--color-accent-fg);
    }
    :global(.prose hr) {
        border-color: var(--color-border);
    }

    :global(.prose thead) {
        border-bottom-color: var(--color-border);
    }
    :global(.prose tbody tr) {
        border-bottom-color: var(--color-border);
    }

    /* Extended markdown */
    :global(.prose mark) {
        background-color: color-mix(
            in srgb,
            var(--color-accent-bg) 25%,
            transparent
        );
        color: inherit;
        border-radius: 2px;
        padding: 0 2px;
    }

    /* Footnotes section generated by marked-footnote */
    :global(.prose .footnotes) {
        margin-top: 1em;
        padding-top: 0.5em;
        border-top: 1px solid var(--color-border);
        font-size: 0.8em;
        color: var(--color-fg-muted);
    }
</style>
