import type { UIMessage, UIMessageChunk } from 'ai';

// Persisted form. Carries everything needed to render an attachment chip and
// look up the bytes by content-hash. Storage lives in the ext's `files` IDB
// store keyed by `hash`, dedup'd via refCount across chats.
export interface AttachmentRef {
    hash: string; // SHA-256 of raw bytes
    name: string;
    mediaType: string;
    sizeBytes: number;
}

// In-flight form. Adds the base64-encoded bytes used by fresh uploads. Bytes
// flow web → ext only on put_message — once stored in the files store, only
// the ref travels.
export interface Attachment extends AttachmentRef {
    encodedSizeBytes: number;
    data: string; // base64
}

// Metadata carried on every CourierUIMessage. `createdAt` drives load-order
// in IDB (compound index reaches into uiMessage.metadata.createdAt) and is
// also surfaced in the UI. `tokens` lands on assistant messages once usage
// is reported and feeds the footer/header indicators.
export interface CourierMessageMetadata {
    createdAt: number;
    tokens?: { input: number; output: number };
}

// Custom `data-*` parts. The only one today is `attachment`: a content-
// addressed reference whose bytes live in the ext's files store, looked up
// via convertDataPart on the way to the provider. Bytes never live in the
// persisted UIMessage — keeps rows small and dedupes across re-uses.
//
// Must satisfy AI SDK's `UIDataTypes = Record<string, unknown>` constraint,
// so we use a `type` with an index signature rather than an `interface`.
export type CourierDataParts = {
    attachment: {
        hash: string;
        name: string;
        mediaType: string;
        sizeBytes: number;
    };
} & Record<string, unknown>;

export type CourierUIMessage = UIMessage<
    CourierMessageMetadata,
    CourierDataParts
>;

export type CourierUIMessageChunk = UIMessageChunk<
    CourierMessageMetadata,
    CourierDataParts
>;

// Persisted form. One IDB row per message, keyPath `['chatId', 'uiMessage.id']`,
// ordered by index `['chatId', 'uiMessage.metadata.createdAt', 'uiMessage.id']`.
export interface StoredMessage {
    chatId: string;
    uiMessage: CourierUIMessage;
}

// In-flight form sent from web → ext via put_message. `freshBlobs` carries
// the base64 bytes for any new `data-attachment` parts whose hash isn't yet
// in the files store. The ext extracts them into the files store and
// persists the message with bare refs. Map keys are the attachment hashes.
export interface HydratedStoredMessage {
    chatId: string;
    uiMessage: CourierUIMessage;
    freshBlobs?: Record<string, { mediaType: string; base64: string }>;
}

// Sent over a port (chrome.runtime.connect) for streaming chat. The 'start'
// message kicks off a turn; the extension owns the turn lifecycle from here
// (lock, stream, append-assistant-message-on-completion). The web can send
// 'stop' mid-stream with `truncateTo` = the visible character count at the
// moment of click; the ext truncates the assembled assistant message to that
// many text chars before saving so the saved row matches what the user saw.
//
// `history` is the pre-turn message state used ONLY for cross-tab broadcast
// (so mirror tabs can render the chat instantly). The extension does NOT
// persist it — user messages and edits are the web's responsibility (via
// put_message / save_meta / etc), the terminal save just appends one new
// assistant row.
export interface TurnStartRequest {
    type: 'start';
    chatId: string;
    sourceTabId: string;
    provider: string;
    model: string;
    // Chat history WITHOUT the trailing assistant placeholder. All
    // `data-attachment` parts must reference hashes already in the ext's
    // files store (the web persists the user message + bytes before
    // sending this request).
    messages: CourierUIMessage[];
    // Optional system prompt; applied via streamText's `system` param.
    system?: string;
    params?: Record<string, unknown>;
    meta: ChatMeta;
    history: StoredMessage[];
    // Stable id for the assistant message the terminal save will append.
    // Generated by the web so it can render the in-progress placeholder
    // under the same id that eventually lands in IDB.
    assistantMessageId: string;
}

export interface TurnStopRequest {
    type: 'stop';
    // Visible text character count at the moment the user clicked stop. The
    // ext truncates the assembled assistant message's text parts to this many
    // chars (in render order) before saving, so what gets persisted matches
    // what the user saw. Parts past the cut are dropped.
    truncateTo: number;
}

// No-op heartbeat sent over the existing stream port while a provider is
// quiet. Chrome MV3 keeps the worker alive when messages move over a port;
// simply having the port open is not enough.
export interface TurnKeepaliveRequest {
    type: 'keepalive';
}

export type TurnRequest =
    | TurnStartRequest
    | TurnStopRequest
    | TurnKeepaliveRequest;

export type StreamErrorSource = 'api' | 'extension';

// Sent from ext → source tab over the turn port. UIMessageChunk passes
// through verbatim — that's the wire protocol. Pre-stream errors (no API
// key, hydrate failure) get their own envelope so we can attribute them
// to the ext rather than the API; in-stream errors arrive as inline
// `{ type: 'error', errorText }` chunks per the AI SDK spec.
export type ExtensionStreamEvent =
    | { type: 'chunk'; chunk: CourierUIMessageChunk }
    | { type: 'done' }
    | { type: 'error'; source: StreamErrorSource; message: string };

// Sent on the long-lived 'broadcast' port from the extension to every
// connected tab so tabs can mirror cross-tab turn lifecycle. The originating
// tab ignores its own turn-start (sourceTabId === own tabId); other events
// are classified by membership in remoteStreamingChatIds.
export type BroadcastEvent =
    | {
          type: 'turn-start';
          chatId: string;
          sourceTabId: string;
          meta: ChatMeta;
          history: StoredMessage[];
          assistantMessageId: string;
      }
    | {
          type: 'turn-chunk';
          chatId: string;
          chunk: CourierUIMessageChunk;
      }
    | { type: 'turn-done'; chatId: string }
    | { type: 'turn-error'; chatId: string; message: string }
    | { type: 'turn-aborted'; chatId: string }
    // Sent immediately after a stop, before turn-done. Mirror tabs snap their
    // assistant placeholder's text parts to `charLen` so every tab shows the
    // same final text — without this, mirror tabs would display all the
    // chunks that arrived before stop and then visibly shrink on the IDB
    // refresh that turn-done triggers.
    | { type: 'turn-truncate'; chatId: string; charLen: number };

// Sent from each connected tab over the broadcast port.
//   - 'register' tags the port with the web's sourceTabId so the extension
//     can skip the source tab when fanning out turn-* events. Single-tab
//     case turns every broadcast into a noop. Sent once, immediately after
//     the port opens.
//   - 'keepalive' is a global heartbeat: as long as any tab has the website
//     open, it resets the SW's 30s idle timer so the worker stays warm for
//     cross-tab fan-out and the next turn.
export interface BroadcastRegisterRequest {
    type: 'register';
    sourceTabId: string;
}
export interface BroadcastKeepaliveRequest {
    type: 'keepalive';
}
export type BroadcastRequest =
    | BroadcastRegisterRequest
    | BroadcastKeepaliveRequest;

export interface UserSettings {
    theme: string;
    fontSizeIndex: number;
    chatWidth: number;
    smoothTextMode: 'smooth' | 'boost-on-complete' | 'dump-on-complete' | 'raw';
    submitKeystroke: 'enter' | 'ctrl+enter';
    modelTier: 'latest' | 'previous' | 'legacy';
    autoscroll: boolean;
    enableWebSearch: boolean;
    providerId: string;
    modelId: string;
    temperature: number;
    maxTokens: number;
    thinkingLevel: string;
    adaptiveThinking: boolean;
    webSearch: boolean;
    tagOpenRouterRequests: boolean;
    // Content hash of the last accepted ToS/Privacy pair. Empty/missing = never agreed.
    legalAcceptedVersion: string;
}

// The mapped-type constraint forces every UserSettings field to appear here —
// adding a field to UserSettings without listing it here is a compile error.
const SETTINGS_KEY_MAP: { [K in keyof UserSettings]: 0 } = {
    theme: 0,
    fontSizeIndex: 0,
    chatWidth: 0,
    smoothTextMode: 0,
    submitKeystroke: 0,
    modelTier: 0,
    autoscroll: 0,
    enableWebSearch: 0,
    providerId: 0,
    modelId: 0,
    temperature: 0,
    maxTokens: 0,
    thinkingLevel: 0,
    adaptiveThinking: 0,
    webSearch: 0,
    tagOpenRouterRequests: 0,
    legalAcceptedVersion: 0,
};
export const SETTINGS_KEYS = Object.keys(
    SETTINGS_KEY_MAP
) as (keyof UserSettings)[];

export interface ChatMeta {
    id: string;
    title: string;
    createdAt: number;
    providerId: string;
    modelId: string;
    temperature: number;
    maxTokens: number;
    thinkingLevel: string;
    adaptiveThinking: boolean;
    webSearch: boolean;
    systemPrompt: string;
}

// Aggregated form: a chat with all its messages, the canonical "load a chat
// for the UI" shape. Assembled by the extension from the meta row + a range
// query on chat_messages.
export interface StoredChat {
    id: string;
    messages: StoredMessage[];
}

// OpenRouter's models API returns rich metadata, so we hydrate the picker at
// runtime instead of curating locally. Lives in the extension's
// chrome.storage.local cache; served to the web via load_openrouter_models.
export interface OpenRouterModel {
    id: string;
    name: string;
    vendor: string;
    contextWindow: number;
    maxOutputTokens: number;
    inputModalities: string[];
    supportedParams: string[];
    free: boolean;
    created: number;
}

// Sent via chrome.runtime.sendMessage for one-off storage operations.
//
// Per-message granularity (put_message / delete_message / delete_messages_after)
// replaces the old blob-style save_chat — writes to disjoint rows don't race,
// so renames/edits/stream-finalize can interleave safely without locks.
export type StorageRequest =
    | { type: 'save_key'; provider: string; apiKey: string }
    | { type: 'clear_key'; provider: string }
    | { type: 'has_keys'; providers: string[] }
    | { type: 'save_settings'; settings: Partial<UserSettings> }
    | { type: 'load_settings' }
    | { type: 'save_meta'; meta: ChatMeta }
    | { type: 'put_message'; message: HydratedStoredMessage }
    | { type: 'delete_message'; chatId: string; messageId: string }
    | { type: 'delete_messages_after'; chatId: string; lastKeptId: string }
    | { type: 'delete_chat'; chatId: string }
    | { type: 'load_chat_metas' }
    | { type: 'load_chats' }
    | { type: 'load_chats_by_ids'; ids: string[] }
    | { type: 'load_chat'; chatId: string }
    | { type: 'load_openrouter_models' }
    | { type: 'get_storage_usage' }
    | { type: 'clear_chats' }
    | { type: 'clear_all' };

// Per-area byte counts shown in Settings → Storage.
export interface StorageUsage {
    localSettingsBytes: number;
    openRouterCacheBytes: number;
    syncSettingsBytes: number;
    chatHistoryBytes: number;
    filesBytes: number;
}

export type StorageResponse =
    | { type: 'saved' }
    | { type: 'has_keys'; saved: Record<string, boolean> }
    | { type: 'settings'; settings: Partial<UserSettings> }
    | { type: 'chat_metas'; metas: ChatMeta[] }
    | { type: 'chats'; chats: StoredChat[] }
    | { type: 'chat'; chat: StoredChat | null }
    | { type: 'openrouter_models'; models: OpenRouterModel[] | null }
    | ({ type: 'storage_usage' } & StorageUsage)
    | { type: 'error'; message: string };
