import type { ProviderOption } from './types';

// NOTE FOR LLMS: NEVER MANUALLY MODIFY IDS/NAMES, THEY ARE CORRECT
export const OPENAI: ProviderOption = {
    id: 'openai',
    name: 'OpenAI',
    models: [
        {
            id: 'gpt-5.5-pro',
            name: 'GPT-5.5 pro',
            params: {
                contextWindow: 1050000,
                maxOutputTokens: 128000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Dec 2025',
            },
        },
        {
            id: 'gpt-5.5',
            name: 'GPT-5.5',
            params: {
                contextWindow: 1050000,
                maxOutputTokens: 128000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Dec 2025',
                thinking: {
                    levels: ['none', 'low', 'medium', 'high', 'xhigh'],
                    defaultLevel: 'medium',
                },
            },
        },
        {
            id: 'gpt-5.4-mini',
            name: 'GPT-5.4 mini',
            params: {
                contextWindow: 400000,
                maxOutputTokens: 128000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Aug 2025',
            },
        },
        {
            id: 'gpt-5.4-nano',
            name: 'GPT-5.4 nano',
            params: {
                contextWindow: 400000,
                maxOutputTokens: 128000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Aug 2025',
            },
        },
        {
            id: 'gpt-5.4',
            name: 'GPT-5.4',
            params: {
                contextWindow: 1050000,
                maxOutputTokens: 128000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Aug 2025',
                thinking: {
                    levels: ['none', 'low', 'medium', 'high', 'xhigh'],
                    defaultLevel: 'none',
                },
            },
        },
        {
            id: 'gpt-5.4-pro',
            name: 'GPT-5.4 pro',
            params: {
                contextWindow: 1050000,
                maxOutputTokens: 128000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Aug 2025',
                thinking: {
                    levels: ['medium', 'high', 'xhigh'],
                    defaultLevel: 'medium',
                },
            },
        },
        {
            id: 'gpt-5.3-chat-latest',
            name: 'GPT-5.3 Chat',
            params: {
                contextWindow: 128000,
                maxOutputTokens: 16384,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Aug 2025',
            },
        },
        {
            id: 'gpt-4o-search-preview',
            name: 'GPT-4o Search Preview',
            params: {
                contextWindow: 128000,
                maxOutputTokens: 16384,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Oct 2023',
            },
        },
        {
            id: 'gpt-5.3-codex',
            name: 'GPT-5.3-Codex',
            params: {
                contextWindow: 400000,
                maxOutputTokens: 128000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Aug 2025',
            },
        },
        {
            id: 'gpt-5.2-codex',
            name: 'GPT-5.2-Codex',
            params: {
                contextWindow: 400000,
                maxOutputTokens: 128000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Aug 2025',
            },
        },
        {
            id: 'gpt-5.2-chat-latest',
            name: 'GPT-5.2 Chat',
            params: {
                contextWindow: 128000,
                maxOutputTokens: 16384,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Aug 2025',
            },
        },
        {
            id: 'gpt-5.2-pro',
            name: 'GPT-5.2 pro',
            params: {
                contextWindow: 400000,
                maxOutputTokens: 128000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Aug 2025',
                thinking: {
                    levels: ['medium', 'high', 'xhigh'],
                    defaultLevel: 'medium',
                },
            },
        },
        {
            id: 'gpt-5.2',
            name: 'GPT-5.2',
            params: {
                contextWindow: 400000,
                maxOutputTokens: 128000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Aug 2025',
                thinking: {
                    levels: ['none', 'low', 'medium', 'high', 'xhigh'],
                    defaultLevel: 'none',
                },
            },
        },
        {
            id: 'gpt-5.1-codex-max',
            name: 'GPT-5.1-Codex-Max',
            params: {
                contextWindow: 400000,
                maxOutputTokens: 128000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Sep 2024',
            },
        },
        {
            id: 'gpt-5.1-codex-mini',
            name: 'GPT-5.1 Codex mini',
            params: {
                contextWindow: 400000,
                maxOutputTokens: 128000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Sep 2024',
            },
        },
        {
            id: 'gpt-5.1-codex',
            name: 'GPT-5.1 Codex',
            params: {
                contextWindow: 400000,
                maxOutputTokens: 128000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Sep 2024',
            },
        },
        {
            id: 'gpt-5.1',
            name: 'GPT-5.1',
            params: {
                contextWindow: 400000,
                maxOutputTokens: 128000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Sep 2024',
                thinking: {
                    levels: ['none', 'low', 'medium', 'high'],
                    defaultLevel: 'none',
                },
            },
        },
        {
            id: 'gpt-5.1-chat-latest',
            name: 'GPT-5.1 Chat',
            params: {
                contextWindow: 128000,
                maxOutputTokens: 16384,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Sep 2024',
            },
        },
        {
            id: 'gpt-5-pro',
            name: 'GPT-5 pro',
            params: {
                contextWindow: 400000,
                maxOutputTokens: 272000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Sep 2024',
            },
        },
        {
            id: 'gpt-5-codex',
            name: 'GPT-5-Codex',
            params: {
                contextWindow: 400000,
                maxOutputTokens: 128000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Sep 2024',
            },
        },
        {
            id: 'gpt-5-nano',
            name: 'GPT-5 nano',
            params: {
                contextWindow: 400000,
                maxOutputTokens: 128000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'May 2024',
            },
        },
        {
            id: 'gpt-5-mini',
            name: 'GPT-5 mini',
            params: {
                contextWindow: 400000,
                maxOutputTokens: 128000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'May 2024',
            },
        },
        {
            id: 'gpt-5',
            name: 'GPT-5',
            params: {
                contextWindow: 400000,
                maxOutputTokens: 128000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Sep 2024',
                thinking: {
                    levels: ['minimal', 'low', 'medium', 'high'],
                    defaultLevel: 'minimal',
                },
            },
        },
        {
            id: 'gpt-5-chat-latest',
            name: 'GPT-5 Chat',
            params: {
                contextWindow: 128000,
                maxOutputTokens: 16384,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Sep 2024',
            },
        },
        {
            id: 'o4-mini-deep-research',
            name: 'o4-mini-deep-research',
            params: {
                contextWindow: 200000,
                maxOutputTokens: 100000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Jun 2024',
            },
        },
        {
            id: 'o3-deep-research',
            name: 'o3-deep-research',
            params: {
                contextWindow: 200000,
                maxOutputTokens: 100000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Jun 2024',
            },
        },
        {
            id: 'o3-pro',
            name: 'o3-pro',
            params: {
                contextWindow: 200000,
                maxOutputTokens: 100000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Jun 2024',
            },
        },
        {
            id: 'gpt-4.1-nano',
            name: 'GPT-4.1 nano',
            params: {
                contextWindow: 1047576,
                maxOutputTokens: 32768,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Jun 2024',
            },
        },
        {
            id: 'gpt-4.1-mini',
            name: 'GPT-4.1 mini',
            params: {
                contextWindow: 1047576,
                maxOutputTokens: 32768,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Jun 2024',
            },
        },
        {
            id: 'gpt-4.1',
            name: 'GPT-4.1',
            params: {
                contextWindow: 1047576,
                maxOutputTokens: 32768,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Jun 2024',
            },
        },
        {
            id: 'o4-mini',
            name: 'o4-mini',
            params: {
                contextWindow: 200000,
                maxOutputTokens: 100000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Jun 2024',
            },
        },
        {
            id: 'o3',
            name: 'o3',
            params: {
                contextWindow: 200000,
                maxOutputTokens: 100000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Jun 2024',
            },
        },
        {
            id: 'o1-pro',
            name: 'o1-pro',
            params: {
                contextWindow: 200000,
                maxOutputTokens: 100000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Oct 2023',
            },
        },
        {
            id: 'gpt-4o-mini-search-preview',
            name: 'GPT-4o mini Search Preview',
            params: {
                contextWindow: 128000,
                maxOutputTokens: 16384,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Oct 2023',
            },
        },
        {
            id: 'gpt-4o',
            name: 'GPT-4o',
            params: {
                contextWindow: 128000,
                maxOutputTokens: 16384,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Oct 2023',
            },
        },
        {
            id: 'o3-mini',
            name: 'o3-mini',
            params: {
                contextWindow: 200000,
                maxOutputTokens: 100000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Oct 2023',
            },
        },
        {
            id: 'o1',
            name: 'o1',
            params: {
                contextWindow: 200000,
                maxOutputTokens: 100000,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Oct 2023',
            },
        },
        {
            id: 'gpt-4o-mini',
            name: 'GPT-4o mini',
            params: {
                contextWindow: 128000,
                maxOutputTokens: 16384,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Oct 2023',
            },
        },
        {
            id: 'gpt-4-turbo',
            name: 'GPT-4 Turbo',
            params: {
                contextWindow: 128000,
                maxOutputTokens: 4096,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Dec 2023',
            },
        },
        {
            id: 'gpt-3.5-turbo-instruct',
            name: 'gpt-3.5-turbo-instruct',
            params: {
                contextWindow: 4096,
                maxOutputTokens: 4096,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Sep 2021',
            },
        },
        {
            id: 'gpt-4',
            name: 'GPT-4',
            params: {
                contextWindow: 8192,
                maxOutputTokens: 8192,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Dec 2023',
            },
        },
        {
            id: 'gpt-3.5-turbo',
            name: 'GPT-3.5 Turbo',
            params: {
                contextWindow: 16385,
                maxOutputTokens: 4096,
                defaultMaxTokens: 8192,
                temperatureMax: 2,
                defaultTemperature: 1,
                knowledgeCutoff: 'Sep 2021',
            },
        },
    ],
};
