<script lang="ts">
	import { renderMarkdown } from './markdown.js';

	let { content }: { content: string } = $props();

	let html = $derived(renderMarkdown(content));
</script>

<div class="prose prose-sm max-w-none">
	<!-- eslint-disable-next-line svelte/no-at-html-tags -->
	{@html html}
</div>

<style>
	/* Code block wrapper — holds the language label + Shiki <pre> */
	:global(.prose .code-block) {
		position: relative;
		margin-top: 0.5em;
		margin-bottom: 0.5em;
	}

	:global(.prose .code-lang) {
		display: inline-block;
		font-family: var(--font-mono);
		font-size: 0.7rem;
		font-style: normal;
		color: var(--color-text-muted);
		padding: 0 2px 4px;
	}

	/* Shiki outputs <pre> with inline background — give it our surface token as fallback */
	:global(.prose pre) {
		background-color: var(--color-surface-sunken);
		border: 1px solid var(--color-border);
		margin-top: 0;
		margin-bottom: 0;
	}

	/* Inline code */
	:global(.prose code:not(pre code)) {
		background-color: var(--color-surface-sunken);
		border: 1px solid var(--color-border);
		border-radius: 4px;
		padding: 1px 5px;
		font-size: 0.8125em;
	}

	/* Remove the backtick pseudo-content typography adds */
	:global(.prose code:not(pre code))::before,
	:global(.prose code:not(pre code))::after {
		content: none;
	}

	:global(.prose blockquote) {
		border-left-color: var(--color-accent);
		color: var(--color-text-muted);
	}

	:global(.prose a) { color: var(--color-accent); }
	:global(.prose hr) { border-color: var(--color-border); }

	:global(.prose thead) { border-bottom-color: var(--color-border); }
	:global(.prose tbody tr) { border-bottom-color: var(--color-border); }

	/* Extended markdown */
	:global(.prose mark) {
		background-color: color-mix(in srgb, var(--color-accent) 25%, transparent);
		color: inherit;
		border-radius: 2px;
		padding: 0 2px;
	}

	/* Footnotes section generated by marked-footnote */
	:global(.prose .footnotes) {
		margin-top: 1em;
		padding-top: 0.5em;
		border-top: 1px solid var(--color-border);
		font-size: 0.8em;
		color: var(--color-text-muted);
	}
</style>
